### ISSUE TITLE
Failed to build transaction: Success - empty transaction

### ISSUE THREAD

**Issue by martbhell** [jeffwidman/ansible-yum-cron#3]
On CentOS 7.2 with default variables in this role I get e-mails every hour containing below:

<pre>
Failed to check for updates with the following error message: 
Failed to build transaction: Success - empty transaction
</pre>

After setting:

<pre>
hourly_update_level: default
</pre>

instead of "security" yum-cron is behaving nicely.

Are you using the yum-cron with security and without errors?

related bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1004853

**Comment by jeffwidman** [comment]
Generally this message means that yum found updates to install, but didn't install them because you asked to only be notified. It will keep emailing you until you run yum update and install or ignore the available packages.

I'm not sure why you're getting an hourly email instead of a daily one though... looking at the defaults, the hourly check should auto-install security updates, notify you, and then not say more until more security updates are available. You should only get a daily alert of potential updates that are non-security updates.

Most common reason for this is you've changed the defaults on hourly so that you're getting notified but yum isn't actually installing the updates. 

If that's not the cause here, then it's most likely the bug you linked to. 

I can't promise I'm not observing this behavior myself, since as soon as I get an email I just login and update manually for non-security ones... I haven't really paid attention to how many emails I get int eh thread since gmail just stacks them up nicely for me.

Also, the package triggering yum notifications is likely related to the OpenSSH vulnerability that came out earlier today... I haven't dug into it, since I patched immediately, but you might try logging in and manually running `yum update` to see what packages you're prompted to update.

I'm closing for now, as this doesn't seem to be a problem with the role, but instead either misconfiguration when you ran it or a bug upstream in yum cron (and most likely outside the scope of this role). If you see anything wrong with the role itself, feel free to reopen.
